version: '3'
services:
  web:
    container_name: web
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "5000:3000"
    volumes:
      - '.:/app'
      - '/app/node_modules'